substitutions:
  name: esphome-web-b1efa4
  friendly_name: Button Lights With Screen

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2024.6.0
  name_add_mac_suffix: false
  project:
    name: esphome.web
    version: dev

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  level: ERROR
  

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

# Allow provisioning Wi-Fi via serial
improv_serial:

wifi:
  # Set up a wifi access point
  ap: {}

# In combination with the `ap` this allows the user
# to provision wifi credentials to the device via WiFi AP.
captive_portal:

dashboard_import:
  package_import_url: github://esphome/example-configs/esphome-web/esp32.yaml@main
  import_full_config: true

# Sets up Bluetooth LE (Only on ESP32) to allow the user
# to provision wifi credentials to the device.
esp32_improv:
  authorizer: none

# To have a "next url" for improv serial
web_server:


globals:
  - id: sequence
    type: int
    initial_value: "0"
    restore_value: "False"

# These components signal presses of the various buttons
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO16
      mode:
        input: true
        pullup: true
      inverted: true
    name: Blue Button
    on_press:
      - delay: 1ms
    id: btn_blue
    filters:
      - delayed_off: 20ms
  - platform: gpio
    pin:
      number: GPIO17
      mode:
        input: true
        pullup: true
      inverted: true
    name: White Button
    id: btn_white
    on_press:
      - delay: 1ms
    filters:
      - delayed_off: 20ms
  - platform: gpio
    pin:
      number: GPIO18
      mode:
        input: true
        pullup: true
      inverted: true
    name: Red Button
    id: btn_red
    on_press:
      - delay: 1ms
    filters:
      - delayed_off: 20ms
  - platform: gpio
    pin:
      number: GPIO19
      mode:
        input: true
        pullup: true
      inverted: true
    name: Yellow Button
    id: btn_yellow
    on_press:
      - delay: 1ms
    filters:
      - delayed_off: 20ms
  - platform: gpio
    pin:
      number: GPIO22
      mode:
        input: true
        pullup: true
      inverted: true
    name: Green Button
    id: btn_green
    on_press:
      - delay: 1ms
    filters:
      - delayed_off: 20ms

# These components set the status of each LED to one of four modes:
# Setting values:
# 0 / OFF
# 1 / ON
# 2 / Slow Flash
# 3 / Fast Flash
number:
  - platform: template
    id: indicator_blue
    name: LED Blue
    max_value: 3
    min_value: 0
    optimistic: True
    step: 1
    mode: BOX           
    initial_value: 0
    restore_value: True
  - platform: template
    id: indicator_white
    name: LED White
    max_value: 3
    min_value: 0
    optimistic: True
    step: 1
    mode: BOX           
    initial_value: 0
    restore_value: True
  - platform: template
    id: indicator_red
    name: LED Red
    max_value: 3
    min_value: 0
    optimistic: True
    step: 1
    mode: BOX           
    initial_value: 0
    restore_value: True
  - platform: template
    id: indicator_yellow
    name: LED Yellow
    max_value: 3
    min_value: 0
    optimistic: True
    step: 1
    mode: BOX           
    initial_value: 0
    restore_value: True
  - platform: template
    id: indicator_green
    name: LED Green
    max_value: 3
    min_value: 0
    optimistic: True
    step: 1
    mode: BOX           
    initial_value: 0
    restore_value: True

interval:
  - id: setter
    interval: 100ms
    then:    
      - lambda: |-
          int seq = id(sequence);
          if (id(indicator_blue).state == 3) {
            if (seq % 2 == 0) id(led_blue).turn_on();
            if (seq % 2 == 1) id(led_blue).turn_off();
          } else if (id(indicator_blue).state == 2) {
            if (seq % 4 == 0) id(led_blue).turn_on();
            if (seq % 4 == 2) id(led_blue).turn_off();
          } else if (id(indicator_blue).state == 1) {
            id(led_blue).turn_on();
          } else {
            id(led_blue).turn_off();
          }
          if (id(indicator_white).state == 3) {
            if (seq % 2 == 0) id(led_white).turn_on();
            if (seq % 2 == 1) id(led_white).turn_off();
          } else if (id(indicator_white).state == 2) {
            if (seq % 4 == 0) id(led_white).turn_on();
            if (seq % 4 == 2) id(led_white).turn_off();
          } else if (id(indicator_white).state == 1) {
            id(led_white).turn_on();
          } else {
            id(led_white).turn_off();
          }
          if (id(indicator_red).state == 3) {
            if (seq % 2 == 0) id(led_red).turn_on();
            if (seq % 2 == 1) id(led_red).turn_off();
          } else if (id(indicator_red).state == 2) {
            if (seq % 4 == 0) id(led_red).turn_on();
            if (seq % 4 == 2) id(led_red).turn_off();
          } else if (id(indicator_red).state == 1) {
            id(led_red).turn_on();
          } else {
            id(led_red).turn_off();
          }
          if (id(indicator_yellow).state == 3) {
            if (seq % 2 == 0) id(led_yellow).turn_on();
            if (seq % 2 == 1) id(led_yellow).turn_off();
          } else if (id(indicator_yellow).state == 2) {
            if (seq % 4 == 0) id(led_yellow).turn_on();
            if (seq % 4 == 2) id(led_yellow).turn_off();
          } else if (id(indicator_yellow).state == 1) {
            id(led_yellow).turn_on();
          } else {
            id(led_yellow).turn_off();
          }
          if (id(indicator_green).state == 3) {
            if (seq % 2 == 0) id(led_green).turn_on();
            if (seq % 2 == 1) id(led_green).turn_off();
          } else if (id(indicator_green).state == 2) {
            if (seq % 4 == 0) id(led_green).turn_on();
            if (seq % 4 == 2) id(led_green).turn_off();
          } else if (id(indicator_green).state == 1) {
            id(led_green).turn_on();
          } else {
            id(led_green).turn_off();
          }
      - globals.set:
          id: sequence
          value: !lambda return (id(sequence) + 1) % 16;
          
switch:
  - platform: gpio
    id: led_blue
    pin: GPIO23
  - platform: gpio
    id: led_white
    pin: GPIO25
  - platform: gpio
    id: led_red
    pin: GPIO26
  - platform: gpio
    id: led_yellow
    pin: GPIO27
  - platform: gpio
    id: led_green
    pin: GPIO33


i2c:
  sda: GPIO21
  scl: GPIO4
  frequency: 800khz

font:
    # gfonts://family[@weight]
  - file: "gfonts://Nanum+Gothic+Coding"
    id: small
    size: 16
  - file: "gfonts://Nanum+Gothic+Coding"
    id: medium
    size: 32
  - file: "gfonts://Nanum+Gothic+Coding"
    id: large
    size: 64


display:
  - platform: ssd1306_i2c
    id: disp
    # show_test_card: true
    model: "SSD1306 128x64"
    address: 0x3C
    lambda: |-

      const char *m1 = id(display_med_1).state.c_str();
      const char *m2 = id(display_med_2).state.c_str();
      const char *m3 = id(display_med_3).state.c_str();
      const char *l1 = id(display_large_1).state.c_str();
      const char *s1 = id(display_small_1).state.c_str();
      const char *s2 = id(display_small_2).state.c_str();
      const char *s3 = id(display_small_3).state.c_str();
      const char *s4 = id(display_small_4).state.c_str();

      it.printf(0, 0, id(small), "%s", s1);
      it.printf(0, 16, id(small), "%s", s2);
      it.printf(0, 32, id(small), "%s", s3);
      it.printf(0, 48, id(small), "%s", s4);
      it.printf(0, 0, id(medium), "%s", m1);
      it.printf(0, 16, id(medium), "%s", m2);
      it.printf(0, 32, id(medium), "%s", m3);
      it.printf(0, 0, id(large), "%s", l1);

    update_interval: 1s
    flip_x: False
    flip_y: False

# These components are used to write on the screen
# Display Line 1 (Large)
# - Max 4 characters, full screen
# Display Line 1/2/3 (Medium)
# - Max 8 characters (Top / Middle / Bottom)
# Display Line 1/2/3/4 (Small)
# - Max 16 characters (Top / Top Middle / Bottom Middle / Bottom)
# Allowed combinations:
# Large - on it's own
# M1 and M3
# S1, S2 and M3
# M1, S3 and S4
# S1, M2 and S4
# S1, S2, S3, S4
# Any other combinations will result in larger lines overwriting smaller
text:
  - platform: template
    id: display_small_1
    name: Display Line 1 (Small)
    optimistic: true
    mode: TEXT
    on_value:
      then:
        - component.update: disp
  - platform: template
    id: display_small_2
    name: Display Line 2 (Small)
    optimistic: true
    mode: TEXT
    on_value:
      then:
        - component.update: disp
  - platform: template
    id: display_small_3
    name: Display Line 3 (Small)
    optimistic: true
    mode: TEXT
    on_value:
      then:
        - component.update: disp
  - platform: template
    id: display_small_4
    name: Display Line 4 (Small)
    optimistic: true
    mode: TEXT
    on_value:
      then:
        - component.update: disp
  - platform: template
    id: display_med_1
    name: Display Line 1 (Medium)
    optimistic: true
    mode: TEXT
    on_value:
      then:
        - component.update: disp
  - platform: template
    id: display_med_2
    name: Display Line 2 (Medium)
    optimistic: true
    mode: TEXT
    on_value:
      then:
        - component.update: disp
  - platform: template
    id: display_med_3
    name: Display Line 3 (Medium)
    optimistic: true
    mode: TEXT
    on_value:
      then:
        - component.update: disp
  - platform: template
    id: display_large_1
    name: Display Line 1 (Large)
    optimistic: true
    mode: TEXT
    on_value:
      then:
        - component.update: disp

# To clear the screen, best do this before changing
# the line format used
button:
  - platform: template
    name: Clear Screen
    id: cls
    icon: "mdi:cancel"
    on_press: 
      then:
        - text.set:
            id: display_small_1
            value: ""                  
        - text.set:
            id: display_small_2
            value: ""                  
        - text.set:
            id: display_small_3
            value: ""                  
        - text.set:
            id: display_small_4
            value: ""                  
        - text.set:
            id: display_med_1
            value: ""                  
        - text.set:
            id: display_med_2
            value: ""         
        - text.set:
            id: display_med_3
            value: ""                           
        - text.set:
            id: display_large_1
            value: ""                  


